# get http://localhost:3100/api/order/check/5


# get http://localhost:3100/api/item_in_order/all/5


# put http://localhost:3100/api/item_in_order/update/
# Content-Type: application/json

# {
#     "order_id": 5,
#     "item_id": 14,
#     "current_amount": 5
# }

# post http://localhost:3100/api/product/create/
# Content-Type: application/json

# {
#     "name": "test",
#     "price": 1500.0,
#     "description": "test",
#     "photo_url": "test",
#     "amount_available": 100,
#     "seller_id": 1,
#     "product_category_id": 1
# }

#get http://localhost:3100/api/product/all
#id = 49




get http://localhost:3100/api/item_in_order/all/1
# post http://localhost:3100/api/item_in_order/create/
# Content-Type: application/json

# {
#     "order_id": 2,
#     "item_id": 49,
#     "current_amount": 1,
#     "status": "Starting to Sparkle"
# }

#delete http://localhost:3100/api/product/49